import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {


  const numCells = 100;
  const columnCount = 10;
  const words = ["APPLE", "BANANA"];
  const alphabet = "abcdefghijklmnopqrstuvwxyz"

  const [letters, setLetters] = useState([]);
  const [rows, setRows] = useState({})

  useEffect(() => {


    setLetters(()=>{
      
      const bigArr = [];
      let arr = [];
      for(let i = 0; i < numCells; i++){

        //arr.push(alphabet[Math.floor(Math.random() * alphabet.length)].toUpperCase())
        arr.push("")
        if(arr.length === columnCount) 
        {
        bigArr.push(arr);
        arr = [];
        }

      }
      return bigArr;
    })
  

  }, []);


  

function findWordInsertLocation(){

  const rowIndex = Math.floor(Math.random() * letters.length)
  const row = letters[rowIndex]
  const cellIndex = Math.floor(Math.random() * row.length)
  return {
    row: rowIndex,
    cell: cellIndex
  };
}

function handleClick(){
  const {row, cell} = findWordInsertLocation();
  setLetters((prev)=>{
    return ([...prev.slice(0,row), [...prev[row].slice(0,cell), "A", ...prev[row].slice(cell+1)], ...prev.slice(row+1)])
  })
}



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>



        <div className={styles.grid}>
          <table className="box"> 
          <tbody>

          {letters.map((arr, index)=>{    
          return <tr row={index} key={Math.random()}>

          {arr.map((letter, index)=>{
          return <td cell={index} key={Math.random()}>{letter}</td>
           })}
                </tr>
          })}

          </tbody>
          </table>
        </div>

        <button onClick={handleClick}>Start</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
