import Head from 'next/head'
import Image from 'next/image'
import Row from '../components/Row.js'
import useWordSearchGrid from '../hooks/useWordSearchGrid';
import {useRef} from 'react'
import styles from '../styles/Home.module.css'


const gridCellCount = 100;
const gridColumnCount = 10;
const words = ["APPLE", "BANANA", "KIWI", "PINEAPPLE", "ORANGE", "MANGO", "STRAWBERRY", "PEAR", "CHERRY", "MELON"];


export default function Home() {

  

const {letters, getRandomLetter} = useWordSearchGrid(gridCellCount, gridColumnCount, words);

const selectedCells = useRef([])

function toggleCellSelected(e){
  console.log(e.target)
  selectedCells.current = [...selectedCells.current, e.target.textContent]
  console.log(selectedCells.current)
}

function handleClick(){
  const cells = document.querySelectorAll(".cell");
  for(let i = 0; i < cells.length; i++){
    if(cells[i].textContent === "Z")
    cells[i].textContent = "";
  }
}


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>



        <div className={styles.grid}>
          <table className="box"> 
          <tbody>

          {letters.map((arr, index)=>{    

            return <Row key={Math.random()} cells={arr} row={index} randomLetter={getRandomLetter} onSelect={toggleCellSelected}/>

          })}

          </tbody>
          </table>



        </div>

        <button onClick={handleClick}>Clicketh!</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
